version: '2' # Must be present exactly once at the beginning of the docker-compose.yml file
services:    # Must be present exactly once at the beginning of the docker-compose.yml file
    video-h264-replay:
        build:
            context: https://github.com/chalmers-revere/opendlv-video-h264-replay.git#v0.0.3
            dockerfile: Dockerfile
        restart: on-failure
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        environment:
        - DISPLAY=${DISPLAY}
        command: "--cid=111 --verbose --name=image /home/li/桌面/dit638/rec_file/CID-140-recording-2020-03-18_144821-selection.rec"
